### ISSUE TITLE
Crash in StructuredFormatting.getMainText

### ISSUE THREAD

**Issue by jamiehiggins** [Drabu/PlaceAutocomplete#3]
Thanks for the library, it saved a lot of time implementing similar. I've just deployed a release with this library in and I'm seeing the following crash (currently Android 8 and 9 but it's early days so that could be irrelevant).

```
Fatal Exception: java.lang.NullPointerException: throw with null exception
       at com.oneclickaway.opensource.placeautocomplete.api.bean.places_response.StructuredFormatting.getMainText(StructuredFormatting.java:3)
       at com.oneclickaway.opensource.placeautocomplete.ui.SearchResultAdapter.onBindViewHolder(SearchResultAdapter.java:31)
       at com.oneclickaway.opensource.placeautocomplete.ui.SearchResultAdapter.onBindViewHolder(SearchResultAdapter.java:16)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
```

**Comment by jamiehiggins** [comment]
Seems to be proguard related. I resolve by adding:

-keep class com.oneclickaway.opensource.placeautocomplete.** {*;}

to my proguard file.
